apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
---
apiVersion: v1
kind: Secret
metadata:
  name: booking-service-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
  redis-url: "redis://redis:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: booking-worker-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
  payment-booking-queue-url: "http://localstack:4566/000000000000/proyecto-final-local-payment-booking-queue"
  aws-region: "us-east-1"
  aws-endpoint-url: "http://localstack:4566"
---
apiVersion: v1
kind: Secret
metadata:
  name: cart-service-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
  redis-url: "redis://redis:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
  redis-url: "redis://redis:6379"
  notification-queue-url: "http://localstack:4566/000000000000/proyecto-final-local-notification-queue"
  aws-region: "us-east-1"
  aws-endpoint-url: "http://localstack:4566"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
  payment-service-url: "http://payment-service:80"
  sns-topic-arn: "arn:aws:sns:us-east-1:000000000000:proyecto-final-local-command-update"
  aws-region: "us-east-1"
  aws-endpoint-url: "http://localstack:4566"
---
apiVersion: v1
kind: Secret
metadata:
  name: reports-service-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
---
apiVersion: v1
kind: Secret
metadata:
  name: commercial-service-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://postgres:postgres@postgres:5432/travelhub"
