apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-infra-config
data:
  redis-url: "redis://redis:6379"
  sqs-queue-url: "http://localstack:4566/000000000000/proyecto-final-local-hotel-sync-queue"
  sns-topic-arn: "arn:aws:sns:us-east-1:000000000000:proyecto-final-local-command-update"
  payment-booking-queue-url: "http://localstack:4566/000000000000/proyecto-final-local-payment-booking-queue"
  notification-queue-url: "http://localstack:4566/000000000000/proyecto-final-local-notification-queue"
  aws-region: "us-east-1"
  aws-endpoint-url: "http://localstack:4566"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-service-discovery
data:
  inventory-service-url: "http://inventory-service:80"
  booking-service-url: "http://booking-service:80"
  cart-service-url: "http://cart-service:80"
  search-service-url: "http://search-service:80"
  notification-service-url: "http://notification-service:80"
  auth-service-url: "http://auth-service:80"
  payment-service-url: "http://payment-service:80"
  reports-service-url: "http://reports-service:80"
  commercial-service-url: "http://commercial-service:80"
