apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-infra-config
data:
  redis-url: "${REDIS_URL}"
  sqs-queue-url: "${SQS_QUEUE_URL}"
  sns-topic-arn: "${SNS_TOPIC_ARN}"
  payment-booking-queue-url: "${PAYMENT_BOOKING_QUEUE_URL}"
  notification-queue-url: "${NOTIFICATION_QUEUE_URL}"
  aws-region: "us-east-1"
  aws-endpoint-url: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-service-discovery
data:
  inventory-service-url: "http://inventory-service:80"
  booking-service-url: "http://booking-service:80"
  cart-service-url: "http://cart-service:80"
  search-service-url: "http://search-service:80"
  notification-service-url: "http://notification-service:80"
  auth-service-url: "http://auth-service:80"
  payment-service-url: "http://payment-service:80"
  reports-service-url: "http://reports-service:80"
  commercial-service-url: "http://commercial-service:80"
