apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::618246140762:role/proyecto-final-dev-notification-service-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      serviceAccountName: notification-service-sa
      containers:
      - name: notification-service
        image: 618246140762.dkr.ecr.us-east-1.amazonaws.com/proyecto-final-dev-notification-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: shared-infra-config
              key: redis-url
        - name: NOTIFICATION_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: shared-infra-config
              key: notification-queue-url
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: shared-infra-config
              key: aws-region
        - name: AWS_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              name: shared-infra-config
              key: aws-endpoint-url
        - name: EXPO_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: notification-service-secrets
              key: expo-access-token
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "130m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
